# This workflow builds the plugin, feature and update site and pushes the update
# site to a dedicated branch called "updatesite" on the Github repo.

name: Build Main

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Push Updatesite
        uses: ingomohr/push-p2-repo-action@v1_0_1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git-user: ${{ github.actor}}
          git-email: ${{ github.actor}}@users.noreply.github.com
          path-to-p2-repo-created-by-maven: 'sites/org.ingomohr.docwriter.updatesite/target'
          path-to-p2-repo-target: 'updatesite'
          commit-message: 'add new updatesite'
          target-branch-name: 'updatesite'


